[package]
name = "mchprs"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"
description = "A multithreaded minecraft server built for redstone."
readme = "README.md"
license = "MIT"
keywords = ["minecraft", "server"]
repository = "https://github.com/StackDoubleFlow/MCHPRS"
homepage = "https://github.com/StackDoubleFlow/MCHPRS"

[badges]
travis-ci = { repository = "StackDoubleFlow/MCHPRS" }

[dependencies]
flate2 = "1.0.14"
byteorder = "1.3.4"
config = "0.10.1"
hematite-nbt = "0.4.1"
bitflags = "1.2.1"
serde = "1.0.106"
md5 = "0.7.0"
bus = "2.2.3"
serde_json = "1.0.51"
arc-swap = "0.4.5"
bincode = "1.2.1"
ctrlc = { version = "3.1.4", features = ["termination"] }
log = "0.4.8"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4"