[package]
name = "mchprs"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.14"
byteorder = "1.3.4"
config = "0.10.1"
hematite-nbt = "0.4.1"
bitflags = "1.2.1"
serde = "1.0.105"
md5 = "0.7.0"
bus = "2.2.3"
serde_json = "1.0.50"
arc-swap = "0.4.5"
